### ISSUE TITLE
`anki-editor-push-notes` hangs on some org files

### ISSUE THREAD

**Issue by Xephobia** [anki-editor/anki-editor#32]
With this org file : 
```
:PROPERTIES:
:ID:       eb1cc3fc-ab69-4739-86f3-63b7442d7b84
:ANKI_DECK: math
:END:
#+title: binomial formula

* definition
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
** Text
the binomial expansion is a way to expand the {{c1::power of a [[id:b9c1a028-adb8-43be-91c8-73d09ba0ae3f][binomial]]}}
** Back Extra
* statement
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:END:
** Text
\( {{c1::( x + y )^n}} = {{c2::\sum_{k=0}^n {n \choose k}}} {{c3::x^{n-k}y^k}} \)
** Back Extra
```
the function runs forever. Here's a profiler output:
[anki-editor-profile.txt](https://github.com/orgtre/anki-editor/files/12092670/anki-editor-profile.txt)

**Comment by evertedsphere** [comment]
Your example notes above don't reproduce the issue for me (the first one works, the second one gives me "beginning of buffer" as an error). 

However, I have run into this issue myself when there is a heading-less / "implicit" field in a card at the end of a file:
```org
* Test
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_DECK: Default
:ANKI_FIELD_EXTRA:
:ANKI_NOTE_ID: 1712396728881
:END:
foo {{c1::bar}}
```

It can be fixed by adding a heading after the end of the text:

```org
* Test
:PROPERTIES:
:ANKI_NOTE_TYPE: Cloze
:ANKI_DECK: Default
:ANKI_FIELD_EXTRA:
:ANKI_NOTE_ID: 1712396728881
:END:
foo {{c1::bar}}
```
This can be a subheading of the card too. It appears to me that anki-editor is searching forward until the next heading for the end of the "implicit" value of the missing field.
