### ISSUE TITLE
Document installation in doom emacs

### ISSUE THREAD

**Issue by andreaskundig** [anki-editor/anki-editor#37]
I managed to install this fork in doom emacs with this snippet in _package.el_. Maybe there is a better way to do it.

``` elisp
(package! anki-editor
  :recipe (:host github :repo "orgtre/anki-editor"
           :fork (:host github :repo "orgtre/anki-editor")))

```

**Comment by Maddogskullcap** [comment]
I followed the Doom [Emacs Getting Started Package Management section](https://github.com/doomemacs/doomemacs/blob/master/docs/getting_started.org#package-management) and used their example for installing packages from external sources:

```
;; To grab a particular branch or tag:
(package! example :recipe
  (:host gitlab
   :repo "username/my-example-fork"
   :branch "develop"))
```

This is what my Doom packages.el looks like, but I've been having issues of my own pushing notes with no *front/*back subheadings as Org-Anki imported everything with the front of the note as the heading and the back as the content of that heading which I prefer anyways, but Anki-editor doesn't seem to like that and outputs `missing fields`, even though the documentation says it should support that note structure. Have you had any issues with that in your Doom? @andreaskundig 
```
(package! anki-editor
   :recipe
  (:host github
   :repo "orgtre/anki-editor"))
```

**Comment by andreaskundig** [comment]
I haven't tried notes without front/back subheadings.

**Comment by evertedsphere** [comment]
```
(package! anki-editor :recipe (:fork "orgtre"))
```
is sufficient.

**Comment by Maddogskullcap** [comment]
Saw this was closed, but I had "issues" installing in doom, when using `doom upgrade`, which I guess I hadn't actually done since declaring anki-editor in packages.el so I think I was still getting the louietan/anki-editor, which is also why I think I had so many issues using this package previously even after I thought I'd switched to the maintained orgtre fork, but maybe not didn't look too much into it. I settled on declaring no host and just using the exact repo link.

```
(package! anki-editor
  :recipe
  (:host nil :repo "https://github.com/anki-editor/anki-editor.git"))
```

During `doom upgrade` it'll say something along the line of upstream is orgtre/anki-editor, but melpa has loutietan/anki-editor as the repo. It'll give a few options for what the user wants to do, the last option is changing the upstream manually. Which i did just inputting the https repo link when it prompts for it which can be found in the "code" dropdown on the github repo. Sorry, I can't give exact details. Once I manually changed the repo it just uses that by default and doesn't force user input anymore which is nice. 

Additionally, I did get the same result when declaring github as the host, but I was trying to find a variation that wouldn't require me to manually change it during the upgrade. The code block I included is the just the one thats in my packages.el.

I'm an emacs novice at the time of commenting so if anyone who knows better sees this as something to avoid as it might causes future complications feel free to educate.

**Comment by slotThe** [comment]
@Maddogskullcap what do you get when you put

``` emacs-lisp
  (package! anki-editor
    :recipe (:host github :repo "anki-editor/anki-editor"))
```

into `packages.el`?

**Comment by Maddogskullcap** [comment]
That's actually what I tried originally, since it seemed the simplest in the documentation. I got the same result as I described above. Unfortunately, even when I change it back to the syntax you described it does not give me the error anymore when running `doom upgrade` now that I've manually changed the remote repo to the correct one. I was hopng it would so I could show exactly what I was seeing. 

Interestingly, in the past when running `doom sync` it never produced an error. So that makes me wonder which remote repo I was actually pulling from in the past and if other doom users are receiving the incorrect repo if they just run a `doom sync` after declaring it in their `packages.el` even when specifying this fork.

I only ran a `doom upgrade` because the last anki note in my org file was not exporting correctly even though I saw that issue had *just* been resolved.
